#!/bin/bash

# YouTube Video Downloader for Windows Desktop
# 自动下载8K/4K/1080p并合并为MP4格式，文件名与视频标题一致
# 用法: ./ytb-download.sh "YouTube_URL" [quality]
# quality 选项: 8k, 4k (默认), 1080p

URL="$1"
QUALITY="${2:-4k}"
DESKTOP="/mnt/d/Users/JINLONG/Desktop"
YTDLP="/tmp/yt-dlp"

# Cookie 文件路径
COOKIES_JSON="/mnt/d/Users/JINLONG/Documents/微云同步助手/个人资料/配置文件/03-安装包/AI agent/youtube_cookies.json"
COOKIES_TXT="/tmp/youtube_cookies.txt"

if [ -z "$URL" ]; then
    echo "用法: $0 \"YouTube_URL\" [quality]"
    echo "quality 选项: 8k, 4k, 1080p (默认: 4k)"
    echo "示例: $0 \"https://www.youtube.com/watch?v=xxxxx\" 8k"
    exit 1
fi

# 转换为小写
QUALITY=$(echo "$QUALITY" | tr '[:upper:]' '[:lower:]')

echo "========== YouTube 下载器 =========="
echo "视频URL: $URL"
echo "画质: $QUALITY"
echo ""

# 检查并更新 cookies
if [ -f "$COOKIES_JSON" ]; then
    echo "从 JSON 更新 cookies..."
    python3 -c "
    import json
    with open('$COOKIES_JSON', 'r') as f:
        cookies = json.load(f)
    with open('$COOKIES_TXT', 'w') as f:
        f.write('# Netscape HTTP Cookie File\n')
        f.write('# This file was generated by Claude Code\n\n')
        for c in cookies:
            domain = c.get('domain', '')
            flag = 'TRUE' if domain.startswith('.') else 'FALSE'
            path = c.get('path', '/')
            secure = 'TRUE' if c.get('secure', False) else 'FALSE'
            expiration = int(c.get('expirationDate', 0))
            name = c.get('name', '')
            value = c.get('value', '')
            f.write(f'{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n')
    "
    echo "Cookies 已更新"
elif [ -f "/mnt/d/Users/JINLONG/Documents/微云同步助手/个人资料/配置文件/03-安装包/AI agent/youtube_cookies.txt" ]; then
    cp "/mnt/d/Users/JINLONG/Documents/微云同步助手/个人资料/配置文件/03-安装包/AI agent/youtube_cookies.txt" "$COOKIES_TXT"
    echo "Cookies 已从 TXT 复制"
fi

# 检查 yt-dlp
if [ ! -f "$YTDLP" ]; then
    echo "正在下载 yt-dlp..."
    curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /tmp/yt-dlp
    chmod +x /tmp/yt-dlp
fi

# 获取视频标题（清理特殊字符）
echo "获取视频信息..."
TITLE=$($YTDLP --js-runtimes node --cookies "$COOKIES_TXT" --get-title "$URL" 2>/dev/null | tr '[:space:]' '_' | tr -d '/:*?"<>|')
echo "标题: $TITLE"
echo ""

# 输出文件
OUTPUT_FINAL="$DESKTOP/${TITLE}.mp4"

# 根据画质选择格式
case "$QUALITY" in
    8k)
        VIDEO_FORMAT="571+140"  # 8K av01 + 音频
        VIDEO_ONLY="571"
        DESC="8K"
        ;;
    4k)
        VIDEO_FORMAT="315+140"  # 4K vp9 + 音频
        VIDEO_ONLY="315"
        DESC="4K"
        ;;
    1080p|1080)
        VIDEO_FORMAT="299+140"  # 1080p60 + 音频
        VIDEO_ONLY="299"
        DESC="1080p60"
        ;;
    *)
        echo "不支持的画质: $QUALITY"
        echo "支持的选项: 8k, 4k, 1080p"
        exit 1
        ;;
esac

echo "========== 尝试下载 $DESC =========="

# 尝试直接下载并合并
$YTDLP --js-runtimes node --cookies "$COOKIES_TXT" --no-part -f "$VIDEO_FORMAT" --merge-output-format mp4 -o "$DESKTOP/${TITLE}.%(ext)s" "$URL"

# 检查是否下载成功
if [ -f "$OUTPUT_FINAL" ]; then
    FILE_SIZE=$(ls -lh "$OUTPUT_FINAL" | awk '{print $5}')
    echo ""
    echo "========== 下载完成！=========="
    echo "文件: ${TITLE}.mp4"
    echo "大小: $FILE_SIZE"
    echo "画质: $DESC"
    echo "位置: $OUTPUT_FINAL"
    exit 0
fi

# 如果上面失败，分开下载
echo ""
echo "========== 直接下载失败，尝试分开下载 =========="

OUTPUT_VIDEO="$DESKTOP/${TITLE}_video.webm"
OUTPUT_AUDIO="$DESKTOP/${TITLE}_audio.m4a"

# 下载视频
echo "下载 $DESC 视频..."
$YTDLP --js-runtimes node --cookies "$COOKIES_TXT" --no-part -f "$VIDEO_ONLY" -o "$OUTPUT_VIDEO" "$URL"

# 下载音频
echo "下载音频..."
$YTDLP --js-runtimes node --cookies "$COOKIES_TXT" --no-part -f "140" -o "$OUTPUT_AUDIO" "$URL"

# 检查文件是否存在
if [ ! -f "$OUTPUT_VIDEO" ] || [ ! -f "$OUTPUT_AUDIO" ]; then
    echo "下载失败！"
    exit 1
fi

# 检查 ffmpeg
FFMPEG="/tmp/ffmpeg-master-latest-linux64-gpl-shared/bin/ffmpeg"
if [ ! -f "$FFMPEG" ]; then
    echo "下载 ffmpeg..."
    curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl-shared.tar.xz -o /tmp/ffmpeg.tar.xz
    cd /tmp && tar -xf ffmpeg.tar.xz
fi

# 合并视频和音频
echo "合并视频和音频..."
export LD_LIBRARY_PATH=/tmp/ffmpeg-master-latest-linux64-gpl-shared/lib:$LD_LIBRARY_PATH
$FFMPEG -i "$OUTPUT_VIDEO" -i "$OUTPUT_AUDIO" -c copy -shortest "$OUTPUT_FINAL"

# 清理临时文件
rm -f "$OUTPUT_VIDEO" "$OUTPUT_AUDIO"

# 检查最终文件
if [ -f "$OUTPUT_FINAL" ]; then
    FILE_SIZE=$(ls -lh "$OUTPUT_FINAL" | awk '{print $5}')
    echo ""
    echo "========== 下载完成！=========="
    echo "文件: ${TITLE}.mp4"
    echo "大小: $FILE_SIZE"
    echo "画质: $DESC"
    echo "位置: $OUTPUT_FINAL"
else
    echo "合并失败！"
    exit 1
fi
